name: Python Setup Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Verificar arquivos alterados
      id: files
      uses: tj-actions/changed-files@v45.0.7
      with:
        files: |
          requirements.txt
          setup.py
          *.py
